## Import Libraries & Load Dataset

In [ ]:
# Block 1: Import Libraries & Load Dataset
# Purpose:
#   - Import required libraries
#   - Define project paths
#   - Load the Customer Personality Analysis dataset
#   - Display a preview of the dataset
# ============================================================

# Import Required Libraries
from pathlib import Path
import pandas as pd
import numpy as np

# ------------------------------------------------------------
# Project Paths
# ------------------------------------------------------------

PROJECT_DIR = Path.cwd()

RAW_DATA_DIR = PROJECT_DIR / "01_Raw_Data"

DATASET_PATH = RAW_DATA_DIR / "marketing_campaign.csv"

# ------------------------------------------------------------
# Load Dataset
# ------------------------------------------------------------

try:
    df = pd.read_csv(DATASET_PATH, sep="\t")

    print("✅ Dataset loaded successfully.\n")

except FileNotFoundError:
    print("❌ Dataset not found.")
    print(f"Expected location:\n{DATASET_PATH}")

# ------------------------------------------------------------
# Preview Dataset
# ------------------------------------------------------------

print("=" * 80)
print("Customer Personality Analysis Dataset")
print("=" * 80)

display(df.head())

print("\nDataset Shape:")
print(df.shape)

print("\nColumn Names:")
display(df.columns.to_frame(name="Columns"))

✅ Dataset loaded successfully.

================================================================================
Customer Personality Analysis Dataset
================================================================================

,ID,Year_Birth,Education,Marital_Status,Income,Kidhome,Teenhome,Dt_Customer,Recency,MntWines,...,NumWebVisitsMonth,AcceptedCmp3,AcceptedCmp4,AcceptedCmp5,AcceptedCmp1,AcceptedCmp2,Complain,Z_CostContact,Z_Revenue,Response
0,5524,1957,Graduation,Single,58138.0,0,0,04-09-2012,58,635,...,7,0,0,0,0,0,0,3,11,1
1,2174,1954,Graduation,Single,46344.0,1,1,08-03-2014,38,11,...,5,0,0,0,0,0,0,3,11,0
2,4141,1965,Graduation,Together,71613.0,0,0,21-08-2013,26,426,...,4,0,0,0,0,0,0,3,11,0
3,6182,1984,Graduation,Together,26646.0,1,0,10-02-2014,26,11,...,6,0,0,0,0,0,0,3,11,0
4,5324,1981,PhD,Married,58293.0,1,0,19-01-2014,94,173,...,5,0,0,0,0,0,0,3,11,0

Dataset Shape:
(2240, 29)

Column Names:

                                 Columns
ID                                    ID
Year_Birth                    Year_Birth
Education                      Education
Marital_Status            Marital_Status
Income                            Income
Kidhome                          Kidhome
Teenhome                        Teenhome
Dt_Customer                  Dt_Customer
Recency                          Recency
MntWines                        MntWines
MntFruits                      MntFruits
MntMeatProducts          MntMeatProducts
MntFishProducts          MntFishProducts
MntSweetProducts        MntSweetProducts
MntGoldProds                MntGoldProds
NumDealsPurchases      NumDealsPurchases
NumWebPurchases          NumWebPurchases
NumCatalogPurchases  NumCatalogPurchases
NumStorePurchases      NumStorePurchases
NumWebVisitsMonth      NumWebVisitsMonth
AcceptedCmp3                AcceptedCmp3
AcceptedCmp4                AcceptedCmp4
AcceptedCmp5                AcceptedCmp5
AcceptedCmp1                AcceptedCmp1
AcceptedCmp2                AcceptedCmp2
Complain                        Complain
Z_CostContact              Z_CostContact
Z_Revenue                      Z_Revenue
Response                        Response

## Dataset Information

In [3]:
# Dataset Information

rows, columns = df.shape

print(f"Rows    : {rows}")
print(f"Columns : {columns}")
print(f"Shape   : {df.shape}")

Rows    : 2240
Columns : 29
Shape   : (2240, 29)

In [4]:
# File Information

import os

file_size = os.path.getsize(DATASET_PATH) / (1024 * 1024)

print(f"File Type : {DATASET_PATH.suffix}")
print(f"File Size : {file_size:.2f} MB")

File Type : .csv
File Size : 0.21 MB

In [5]:
inspection_summary = pd.DataFrame({
    "Property": [
        "Rows",
        "Columns",
        "File Type",
        "Dataset Size (MB)"
    ],
    "Value": [
        rows,
        columns,
        DATASET_PATH.suffix,
        round(file_size, 2)
    ]
})

inspection_summary

            Property Value
0               Rows  2240
1            Columns    29
2          File Type  .csv
3  Dataset Size (MB)  0.21

In [8]:
import sys
!{sys.executable} -m pip install openpyxl

Collecting openpyxl
  Using cached openpyxl-3.1.5-py2.py3-none-any.whl.metadata (2.5 kB)
Collecting et-xmlfile (from openpyxl)
  Using cached et_xmlfile-2.0.0-py3-none-any.whl.metadata (2.7 kB)
Using cached openpyxl-3.1.5-py2.py3-none-any.whl (250 kB)
Using cached et_xmlfile-2.0.0-py3-none-any.whl (18 kB)
Installing collected packages: et-xmlfile, openpyxl
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2/2 [openpyxl]1/2 [openpyxl]
Successfully installed et-xmlfile-2.0.0 openpyxl-3.1.5

[notice] A new release of pip is available: 25.3 -> 26.1.2
[notice] To update, run: python -m pip install --upgrade pip

In [ ]:
from pathlib import Path

PROJECT_DIR = Path.cwd()

output_path = PROJECT_DIR / "02_Inspection_Report" / "basic_dataset_inspection.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

inspection_summary.to_excel(output_path, index=False)

print(f"✅ Report saved successfully at:\n{output_path}")

## Variable Inspection

In [10]:
# Display all column names

columns = pd.DataFrame({
    "Column Name": df.columns
})

columns

            Column Name
0                    ID
1            Year_Birth
2             Education
3        Marital_Status
4                Income
5               Kidhome
6              Teenhome
7           Dt_Customer
8               Recency
9              MntWines
10            MntFruits
11      MntMeatProducts
12      MntFishProducts
13     MntSweetProducts
14         MntGoldProds
15    NumDealsPurchases
16      NumWebPurchases
17  NumCatalogPurchases
18    NumStorePurchases
19    NumWebVisitsMonth
20         AcceptedCmp3
21         AcceptedCmp4
22         AcceptedCmp5
23         AcceptedCmp1
24         AcceptedCmp2
25             Complain
26        Z_CostContact
27            Z_Revenue
28             Response

In [11]:
# Display data types of each column

data_types = pd.DataFrame({
    "Column Name": df.columns,
    "Data Type": df.dtypes.values.astype(str)
})

data_types

            Column Name Data Type
0                    ID     int64
1            Year_Birth     int64
2             Education    object
3        Marital_Status    object
4                Income   float64
5               Kidhome     int64
6              Teenhome     int64
7           Dt_Customer    object
8               Recency     int64
9              MntWines     int64
10            MntFruits     int64
11      MntMeatProducts     int64
12      MntFishProducts     int64
13     MntSweetProducts     int64
14         MntGoldProds     int64
15    NumDealsPurchases     int64
16      NumWebPurchases     int64
17  NumCatalogPurchases     int64
18    NumStorePurchases     int64
19    NumWebVisitsMonth     int64
20         AcceptedCmp3     int64
21         AcceptedCmp4     int64
22         AcceptedCmp5     int64
23         AcceptedCmp1     int64
24         AcceptedCmp2     int64
25             Complain     int64
26        Z_CostContact     int64
27            Z_Revenue     int64
28             Response     int64

In [12]:
# Add descriptions for each variable

descriptions = [
    "Unique customer identifier",
    "Year customer was born",
    "Education level",
    "Marital status",
    "Annual household income",
    "Number of children at home",
    "Number of teenagers at home",
    "Customer enrollment date",
    "Days since last purchase",
    "Amount spent on wine",
    "Amount spent on fruits",
    "Amount spent on meat products",
    "Amount spent on fish products",
    "Amount spent on sweet products",
    "Amount spent on gold products",
    "Number of discount purchases",
    "Number of web purchases",
    "Number of catalog purchases",
    "Number of store purchases",
    "Number of website visits per month",
    "Accepted campaign 3",
    "Accepted campaign 4",
    "Accepted campaign 5",
    "Accepted campaign 1",
    "Accepted campaign 2",
    "Customer complaint status",
    "Cost to company",
    "Revenue generated",
    "Response to last campaign"
]

variable_inspection = pd.DataFrame({
    "Variable": df.columns,
    "Data Type": df.dtypes.values.astype(str),
    "Description": descriptions
})

variable_inspection

               Variable Data Type                         Description
0                    ID     int64          Unique customer identifier
1            Year_Birth     int64              Year customer was born
2             Education    object                     Education level
3        Marital_Status    object                      Marital status
4                Income   float64             Annual household income
5               Kidhome     int64          Number of children at home
6              Teenhome     int64         Number of teenagers at home
7           Dt_Customer    object            Customer enrollment date
8               Recency     int64            Days since last purchase
9              MntWines     int64                Amount spent on wine
10            MntFruits     int64              Amount spent on fruits
11      MntMeatProducts     int64       Amount spent on meat products
12      MntFishProducts     int64       Amount spent on fish products
13     MntSweetProducts     int64      Amount spent on sweet products
14         MntGoldProds     int64       Amount spent on gold products
15    NumDealsPurchases     int64        Number of discount purchases
16      NumWebPurchases     int64             Number of web purchases
17  NumCatalogPurchases     int64         Number of catalog purchases
18    NumStorePurchases     int64           Number of store purchases
19    NumWebVisitsMonth     int64  Number of website visits per month
20         AcceptedCmp3     int64                 Accepted campaign 3
21         AcceptedCmp4     int64                 Accepted campaign 4
22         AcceptedCmp5     int64                 Accepted campaign 5
23         AcceptedCmp1     int64                 Accepted campaign 1
24         AcceptedCmp2     int64                 Accepted campaign 2
25             Complain     int64           Customer complaint status
26        Z_CostContact     int64                     Cost to company
27            Z_Revenue     int64                   Revenue generated
28             Response     int64           Response to last campaign

In [ ]:
# Save the variable inspection report

output_path = PROJECT_DIR / "02_Inspection_Report" / "variable_inspection.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

variable_inspection.to_excel(output_path, index=False)

print("✅ Variable Inspection Report Saved!")
print(output_path)

## Missing Value Analysis

In [14]:
# Count missing values in each column

missing_values = df.isnull().sum()

missing_values

ID                      0
Year_Birth              0
Education               0
Marital_Status          0
Income                 24
Kidhome                 0
Teenhome                0
Dt_Customer             0
Recency                 0
MntWines                0
MntFruits               0
MntMeatProducts         0
MntFishProducts         0
MntSweetProducts        0
MntGoldProds            0
NumDealsPurchases       0
NumWebPurchases         0
NumCatalogPurchases     0
NumStorePurchases       0
NumWebVisitsMonth       0
AcceptedCmp3            0
AcceptedCmp4            0
AcceptedCmp5            0
AcceptedCmp1            0
AcceptedCmp2            0
Complain                0
Z_CostContact           0
Z_Revenue               0
Response                0
dtype: int64

In [15]:
# Calculate missing value percentage

missing_percentage = (df.isnull().sum() / len(df)) * 100

missing_percentage

ID                     0.000000
Year_Birth             0.000000
Education              0.000000
Marital_Status         0.000000
Income                 1.071429
Kidhome                0.000000
Teenhome               0.000000
Dt_Customer            0.000000
Recency                0.000000
MntWines               0.000000
MntFruits              0.000000
MntMeatProducts        0.000000
MntFishProducts        0.000000
MntSweetProducts       0.000000
MntGoldProds           0.000000
NumDealsPurchases      0.000000
NumWebPurchases        0.000000
NumCatalogPurchases    0.000000
NumStorePurchases      0.000000
NumWebVisitsMonth      0.000000
AcceptedCmp3           0.000000
AcceptedCmp4           0.000000
AcceptedCmp5           0.000000
AcceptedCmp1           0.000000
AcceptedCmp2           0.000000
Complain               0.000000
Z_CostContact          0.000000
Z_Revenue              0.000000
Response               0.000000
dtype: float64

In [16]:
# Create a missing values report

missing_report = pd.DataFrame({
    "Variable": df.columns,
    "Missing Values": df.isnull().sum().values,
    "Percentage (%)": ((df.isnull().sum() / len(df)) * 100).round(2).values
})

missing_report

               Variable  Missing Values  Percentage (%)
0                    ID               0            0.00
1            Year_Birth               0            0.00
2             Education               0            0.00
3        Marital_Status               0            0.00
4                Income              24            1.07
5               Kidhome               0            0.00
6              Teenhome               0            0.00
7           Dt_Customer               0            0.00
8               Recency               0            0.00
9              MntWines               0            0.00
10            MntFruits               0            0.00
11      MntMeatProducts               0            0.00
12      MntFishProducts               0            0.00
13     MntSweetProducts               0            0.00
14         MntGoldProds               0            0.00
15    NumDealsPurchases               0            0.00
16      NumWebPurchases               0            0.00
17  NumCatalogPurchases               0            0.00
18    NumStorePurchases               0            0.00
19    NumWebVisitsMonth               0            0.00
20         AcceptedCmp3               0            0.00
21         AcceptedCmp4               0            0.00
22         AcceptedCmp5               0            0.00
23         AcceptedCmp1               0            0.00
24         AcceptedCmp2               0            0.00
25             Complain               0            0.00
26        Z_CostContact               0            0.00
27            Z_Revenue               0            0.00
28             Response               0            0.00

In [17]:
# Display columns without missing values

no_missing = missing_report[missing_report["Missing Values"] == 0]

no_missing

               Variable  Missing Values  Percentage (%)
0                    ID               0             0.0
1            Year_Birth               0             0.0
2             Education               0             0.0
3        Marital_Status               0             0.0
5               Kidhome               0             0.0
6              Teenhome               0             0.0
7           Dt_Customer               0             0.0
8               Recency               0             0.0
9              MntWines               0             0.0
10            MntFruits               0             0.0
11      MntMeatProducts               0             0.0
12      MntFishProducts               0             0.0
13     MntSweetProducts               0             0.0
14         MntGoldProds               0             0.0
15    NumDealsPurchases               0             0.0
16      NumWebPurchases               0             0.0
17  NumCatalogPurchases               0             0.0
18    NumStorePurchases               0             0.0
19    NumWebVisitsMonth               0             0.0
20         AcceptedCmp3               0             0.0
21         AcceptedCmp4               0             0.0
22         AcceptedCmp5               0             0.0
23         AcceptedCmp1               0             0.0
24         AcceptedCmp2               0             0.0
25             Complain               0             0.0
26        Z_CostContact               0             0.0
27            Z_Revenue               0             0.0
28             Response               0             0.0

In [ ]:
# Save the report

output_path = PROJECT_DIR / "03_Data_Quality" / "missing_values_report.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

missing_report.to_excel(output_path, index=False)

print("✅ Missing Values Report Saved!")
print(output_path)

## Duplicate Record Analysis

In [19]:
# Count duplicate rows

duplicate_rows = df.duplicated().sum()

print(f"Duplicate Rows: {duplicate_rows}")

Duplicate Rows: 0

In [ ]:
# Check duplicate customer IDs

duplicate_ids = df["ID"].duplicated().sum()

print(f"Duplicate Customer IDs: {duplicate_ids}")

In [52]:
# Create duplicate report

duplicate_report = pd.DataFrame({
    "Check": [
        "Duplicate Rows",
        "Duplicate Customer IDs"
    ],
    "Count": [
        duplicate_rows,
        duplicate_ids
    ]
})

duplicate_report

                    Check  Count
0          Duplicate Rows      0
1  Duplicate Customer IDs      0

In [ ]:
# Save duplicate report

output_path = PROJECT_DIR / "03_Data_Quality" / "duplicate_report.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

duplicate_report.to_excel(output_path, index=False)

print("✅ Duplicate Report Saved!")
print(output_path)

## Data Quality Checks

In [ ]:
# Check for unrealistic Year_Birth values (customers older than 100 years)

current_year = 2014  # last enrollment year in the dataset

customer_age = current_year - df["Year_Birth"]  # temporary variable, not added to df

invalid_age_count = (customer_age > 100).sum()

print(f"Customers older than 100 years: {invalid_age_count}")
print("\nOldest Year_Birth values:")
print(df["Year_Birth"].sort_values().head())

In [ ]:
# Check for invalid or extreme Income values

negative_income_count = (df["Income"] < 0).sum()

high_income_threshold = 600000
high_income_count = (df["Income"] > high_income_threshold).sum()

print(f"Negative Income values: {negative_income_count}")
print(f"Income values above {high_income_threshold}: {high_income_count}")
print(f"Maximum Income value: {df['Income'].max()}")

In [ ]:
# Check for inconsistent Marital_Status categories

marital_categories = df["Marital_Status"].unique()

print("Marital_Status categories found:")
print(marital_categories)

unusual_marital_values = ["Absurd", "YOLO", "Alone"]
unusual_marital_count = df["Marital_Status"].isin(unusual_marital_values).sum()

print(f"\nRows with unusual Marital_Status values: {unusual_marital_count}")

In [ ]:
# Create incorrect values report

incorrect_values_report = pd.DataFrame({
    "Check": [
        "Customers older than 100 years (Year_Birth)",
        "Negative Income values",
        "Income values above 600000",
        "Unusual Marital_Status categories (Absurd, YOLO, Alone)"
    ],
    "Count": [
        invalid_age_count,
        negative_income_count,
        high_income_count,
        unusual_marital_count
    ]
})

incorrect_values_report

In [ ]:
# Save incorrect values report

output_path = PROJECT_DIR / "03_Data_Quality" / "incorrect_values_report.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

incorrect_values_report.to_excel(output_path, index=False)

print("✅ Incorrect Values Report Saved!")
print(output_path)

## Numerical Variable Summary

In [30]:
# Identify numerical columns

numerical_columns = df.select_dtypes(include=['number']).columns

print("Number of Numerical Variables:", len(numerical_columns))
print("\nNumerical Variables:\n")

for column in numerical_columns:
    print(column)

Number of Numerical Variables: 27

Numerical Variables:

ID
Year_Birth
Income
Kidhome
Teenhome
Recency
MntWines
MntFruits
MntMeatProducts
MntFishProducts
MntSweetProducts
MntGoldProds
NumDealsPurchases
NumWebPurchases
NumCatalogPurchases
NumStorePurchases
NumWebVisitsMonth
AcceptedCmp3
AcceptedCmp4
AcceptedCmp5
AcceptedCmp1
AcceptedCmp2
Complain
Z_CostContact
Z_Revenue
Response
Age

In [ ]:
# Generate summary statistics

numerical_summary = pd.DataFrame({
    "Variable": numerical_columns,
    "Minimum": df[numerical_columns].min().values,
    "Maximum": df[numerical_columns].max().values,
    "Mean": df[numerical_columns].mean().round(2).values
})

numerical_summary

In [ ]:
# Add simple observations

observations = []

for column in numerical_columns:
    minimum = df[column].min()
    maximum = df[column].max()

    observations.append(f"Values range from {minimum} to {maximum}")

numerical_summary["Observation"] = observations

numerical_summary

In [ ]:
# Save numerical summary

output_path = PROJECT_DIR / "02_Inspection_Report" / "numerical_variables_summary.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

numerical_summary.to_excel(output_path, index=False)

print("✅ Numerical Variables Summary Saved Successfully!")
print(output_path)

## Categorical Variable Summary

In [34]:
# Identify categorical columns

categorical_columns = df.select_dtypes(include=["object"]).columns

print("Number of Categorical Variables:", len(categorical_columns))
print("\nCategorical Variables:\n")

for column in categorical_columns:
    print(column)

Number of Categorical Variables: 2

Categorical Variables:

Education
Marital_Status

In [35]:
# Display unique categories for each categorical variable

for column in categorical_columns:
    print(f"\n{'='*50}")
    print(f"{column}")
    print(f"{'='*50}")
    print(df[column].unique())

==================================================
Education
==================================================
['Graduation' 'PhD' 'Master' 'Basic' '2n Cycle']

==================================================
Marital_Status
==================================================
['Single' 'Together' 'Married' 'Divorced' 'Widow' 'Alone' 'Absurd' 'YOLO']

In [36]:
# Create categorical summary table

categorical_summary = pd.DataFrame({
    "Variable": categorical_columns,
    "Number of Categories": [df[col].nunique() for col in categorical_columns],
    "Categories": [
        ", ".join(map(str, sorted(df[col].dropna().unique())))
        for col in categorical_columns
    ]
})

categorical_summary

,Variable,Number of Categories,Categories
0,Education,5,"2n Cycle, Basic, Graduation, Master, PhD"
1,Marital_Status,8,"Absurd, Alone, Divorced, Married, Single, Toge..."

In [ ]:
# Save categorical summary

output_path = PROJECT_DIR / "02_Inspection_Report" / "categorical_variables_summary.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

categorical_summary.to_excel(output_path, index=False)

print("✅ Categorical Variables Summary Saved Successfully!")
print(output_path)

## Business Indicator Exploration

In [39]:
# Business Indicators

business_indicators = pd.DataFrame({
    "Business Indicator": [
        "High Income Customers",
        "Frequent Buyers",
        "Campaign Responders",
        "Customers with Complaints",
        "Website Visitors",
        "High Spending Customers",
        "Recently Active Customers"
    ],
    "Explanation": [
        "Customers with high annual income who may have greater purchasing power.",
        "Customers who make purchases frequently through different sales channels.",
        "Customers who accepted one or more marketing campaigns.",
        "Customers who have submitted complaints about products or services.",
        "Customers who visit the company website frequently, indicating online engagement.",
        "Customers who spend large amounts on products across different categories.",
        "Customers who made a purchase recently, indicating active engagement."
    ]
})

business_indicators

,Business Indicator,Explanation
0,High Income Customers,Customers with high annual income who may have...
1,Frequent Buyers,Customers who make purchases frequently throug...
2,Campaign Responders,Customers who accepted one or more marketing c...
3,Customers with Complaints,Customers who have submitted complaints about ...
4,Website Visitors,Customers who visit the company website freque...
5,High Spending Customers,Customers who spend large amounts on products ...
6,Recently Active Customers,"Customers who made a purchase recently, indica..."

In [ ]:
# Save business indicators

output_path = PROJECT_DIR / "06_Final_Report" / "business_understanding.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

business_indicators.to_excel(output_path, index=False)

print("✅ Business Understanding Report Saved Successfully!")
print(output_path)

## Initial Data Summary

In [41]:
# Count variable types

num_variables = len(df.select_dtypes(include=["number"]).columns)
cat_variables = len(df.select_dtypes(include=["object"]).columns)

print("Numerical Variables :", num_variables)
print("Categorical Variables :", cat_variables)

Numerical Variables : 27
Categorical Variables : 2

In [42]:
# Create initial data summary

initial_summary = pd.DataFrame({
    "Item": [
        "Dataset Name",
        "Number of Records",
        "Number of Variables",
        "Numerical Variables",
        "Categorical Variables",
        "Missing Values",
        "Duplicate Rows",
        "Major Data Quality Issues"
    ],
    "Summary": [
        "Customer Personality Analysis",
        len(df),
        df.shape[1],
        num_variables,
        cat_variables,
        df.isnull().sum().sum(),
        duplicate_rows,
        "Missing values, duplicate records, invalid ages, negative income and inconsistent categories were reviewed."
    ]
})

initial_summary

,Item,Summary
0,Dataset Name,Customer Personality Analysis
1,Number of Records,2240
2,Number of Variables,30
3,Numerical Variables,27
4,Categorical Variables,2
5,Missing Values,24
6,Duplicate Rows,0
7,Major Data Quality Issues,"Missing values, duplicate records, invalid age..."

In [ ]:
# Save initial data summary

output_path = PROJECT_DIR / "06_Final_Report" / "initial_data_summary.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

initial_summary.to_excel(output_path, index=False)

print("✅ Initial Data Summary Saved Successfully!")
print(output_path)

## Data Dictionary

In [ ]:
# Keep a reference copy of the original loaded dataset (no changes made to it)

original_df = df.copy()

In [ ]:
# Add business meaning for each variable

business_meaning = [
    "Used to uniquely identify each customer record",
    "Helps calculate customer age and generational segments",
    "Indicates customer education level for segmentation",
    "Indicates customer relationship status for targeting",
    "Key indicator of purchasing power and spending potential",
    "Helps understand household structure and product needs",
    "Helps understand household structure and product needs",
    "Indicates customer tenure with the company",
    "Indicates customer engagement and activity level",
    "Shows spending pattern in the wine category",
    "Shows spending pattern in the fruit category",
    "Shows spending pattern in the meat category",
    "Shows spending pattern in the fish category",
    "Shows spending pattern in the sweets category",
    "Shows spending pattern in the gold category",
    "Indicates response to discount-based promotions",
    "Indicates preference for online shopping",
    "Indicates preference for catalog shopping",
    "Indicates preference for in-store shopping",
    "Indicates online engagement and browsing behavior",
    "Shows response to the 3rd marketing campaign",
    "Shows response to the 4th marketing campaign",
    "Shows response to the 5th marketing campaign",
    "Shows response to the 1st marketing campaign",
    "Shows response to the 2nd marketing campaign",
    "Helps identify customer satisfaction issues",
    "Used in campaign cost-benefit analysis",
    "Used in campaign cost-benefit analysis",
    "Indicates response to the most recent marketing campaign"
]

In [48]:
print("Columns           :", len(original_df.columns))
print("Descriptions      :", len(descriptions))
print("Business Meaning  :", len(business_meaning))

Columns           : 29
Descriptions      : 30
Business Meaning  : 30

In [49]:
print(list(original_df.columns))

['ID', 'Year_Birth', 'Education', 'Marital_Status', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer', 'Recency', 'MntWines', 'MntFruits', 'MntMeatProducts', 'MntFishProducts', 'MntSweetProducts', 'MntGoldProds', 'NumDealsPurchases', 'NumWebPurchases', 'NumCatalogPurchases', 'NumStorePurchases', 'NumWebVisitsMonth', 'AcceptedCmp3', 'AcceptedCmp4', 'AcceptedCmp5', 'AcceptedCmp1', 'AcceptedCmp2', 'Complain', 'Z_CostContact', 'Z_Revenue', 'Response']

In [50]:
for i, item in enumerate(descriptions, start=1):
    print(i, item)

1 Unique customer identifier
2 Year of birth
3 Customer education level
4 Customer marital status
5 Annual household income
6 Number of children at home
7 Number of teenagers at home
8 Customer enrollment date
9 Days since last purchase
10 Amount spent on wine
11 Amount spent on fruits
12 Amount spent on meat products
13 Amount spent on fish products
14 Amount spent on sweet products
15 Amount spent on gold products
16 Number of purchases made using discounts
17 Number of purchases made through the website
18 Number of purchases made through catalogs
19 Number of purchases made in stores
20 Number of website visits in the last month
21 Accepted Campaign 3
22 Accepted Campaign 4
23 Accepted Campaign 5
24 Accepted Campaign 1
25 Accepted Campaign 2
26 Customer complaint status
27 Cost to the company
28 Revenue generated
29 Accepted the last campaign
30 Customer age

In [ ]:
# Print business meaning for each variable

for i, item in enumerate(business_meaning, start=1):
    print(i, item)

In [ ]:
# Build the complete data dictionary

data_dictionary = pd.DataFrame({
    "Column": original_df.columns,
    "Data Type": original_df.dtypes.values.astype(str),
    "Description": descriptions,
    "Business Meaning": business_meaning
})

data_dictionary

In [ ]:
# Save the data dictionary

output_path = PROJECT_DIR / "04_Data_Dictionary" / "data_dictionary.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

data_dictionary.to_excel(output_path, index=False)

print("✅ Data Dictionary Saved Successfully!")
print(output_path)

## Data Quality Report

In [ ]:
# Build the overall Data Quality Report

data_quality_report = pd.DataFrame({
    "Check": [
        "Total Rows",
        "Total Columns",
        "Total Missing Values",
        "Duplicate Rows",
        "Duplicate Customer IDs",
        "Customers older than 100 years",
        "Negative Income values",
        "Unusual Marital_Status categories"
    ],
    "Result": [
        len(df),
        df.shape[1],
        df.isnull().sum().sum(),
        duplicate_rows,
        duplicate_ids,
        invalid_age_count,
        negative_income_count,
        unusual_marital_count
    ]
})

data_quality_report

In [ ]:
# Save the Data Quality Report

output_path = PROJECT_DIR / "03_Data_Quality" / "data_quality_report.xlsx"
output_path.parent.mkdir(parents=True, exist_ok=True)

data_quality_report.to_excel(output_path, index=False)

print("✅ Data Quality Report Saved Successfully!")
print(output_path)

## Save Reports

In [ ]:
# Summary of all saved reports

print("All reports have been saved to the project folders:")
print("- 02_Inspection_Report")
print("- 03_Data_Quality")
print("- 04_Data_Dictionary")
print("- 06_Final_Report")